#include "musicplayer.h"
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QSlider>
#include <QLabel>
#include <QPushButton>
#include <QListWidget>
#include <QFrame>
#include <QFileDialog>
#include <QPainter>
#include <QPainterPath>
#include <QLinearGradient>
#include <QStandardPaths>
#include <QFileInfo>
#include <QRandomGenerator>
#include <QTime>
#include <QSizePolicy>
#include <QFont>
#include <QColor>
